export default {
    anchor: true,
    align: false,
    alignWide: false,
    className: false,
    color: false,
    customClassName: false,
    defaultStylePicker: false,
    fontSize: false,
    html: false,
    inserter: true,
    lineHeight: false,
    multiple: true,
    reusable: true,
    padding: true,
}
