export default supports = {
    anchor: true,
    align: false,
    alignWide: false,
    className: false,
    color: true,
    customClassName: false,
    defaultStylePicker: false,
    fontSize: false,
    html: false,
    inserter: false,
    lineHeight: false,
    multiple: true,
    reusable: true,
    padding: true,
}
